# Generated by Django 3.2.6 on 2021-12-07 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211207_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 17, 26, 5, 205744, tzinfo=utc)),
        ),
    ]
