# Generated by Django 3.2.6 on 2021-12-08 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211208_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 10, 0, 10, 89987, tzinfo=utc)),
        ),
    ]
