# Generated by Django 3.2.6 on 2021-12-09 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20211209_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 10, 11, 4, 21867, tzinfo=utc)),
        ),
    ]
