# Generated by Django 3.2.6 on 2021-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_guest_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
