# Generated by Django 3.2.6 on 2021-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20210827_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='booked_room',
            field=models.ManyToManyField(blank=True, related_name='booked_room', to='show.Room'),
        ),
    ]
